name: deploy

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Produce docker-compose.yml for deploy
        run: |
          ghcr="ghcr.io/${{ github.repository }}"
          echo "ghcr=${ghcr,,}" >> $GITHUB_ENV
          repo=$(echo "${ghcr}" | cut -d'/' -f3)
          sed -e "s|\${GHCR}|${ghcr}|g" \
              -e "s|\${REPO}|${repo}|g" \
              "${{ inputs.path }}" > docker-compose.yml

      - name: Upload docker-compose.yml to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: docker-compose.yml
          tag: refs/tags/${{ inputs.version }}
          overwrite: true