name: deploy

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Convert tags to lowercase
        run: |
          ghcr_tag="ghcr.io/${{ github.repository }}"
          repository="${{ github.repository }}"
          repo_name="${repository#*/}"
          echo "ghcr_tag=${ghcr_tag,,}" >> $GITHUB_ENV
          echo "repo_name=${repo_name,,}" >> $GITHUB_ENV

      - name: Produce docker-compose.yml for deploy
        run: |
          sed -e "s|\${GHCR}|${ghcr_tag}|g" \
              -e "s|\${REPO}|${repo_name}|g" \
              "${{ inputs.path }}" > docker-compose.yml

      - name: Upload docker-compose.yml to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: docker-compose.yml
          tag: refs/tags/${{ inputs.version }}
          overwrite: true