name: publish

on:
  workflow_call:
    inputs:
      path:
        default: 'Cargo.toml'
        required: true
        type: string

jobs:
  parse:
    uses: ./.github/workflows/parse.yml
    with:
      path: ${{ inputs.path }}
  tag:
    needs:
      - parse
    uses: ./.github/workflows/tag.yml
    with:
      version: ${{ needs.parse.outputs.version }}
  release:
    needs:
      - tag
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.tag.outputs.version }}
      note: "add release for ${{ needs.tag.outputs.version }}"
  compose:
    uses: ./.github/workflows/deploy.yml
    with:
      path: docker/docker-compose.yml
      name: ${{ github.repository }}

  matrix-release:
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            platform: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            platform: ubuntu-latest
          - target: powerpc64le-unknown-linux-musl
            platform: ubuntu-latest
    with:
      path: ${{ inputs.path }}
      target: ${{ matrix.target }}
      platform: ${{ matrix.platform }}
