name: tag

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_call:
    inputs:
      version:
        default: '0'
        required: true
        type: string
    outputs:
      version:
        description: "Pushed tag version"
        value: ${{ jobs.tag.outputs.version }}

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.push.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - id: push
        run: |
          version="${{ inputs.version }}"
          git tag $version && git push --tags || true
          echo version=$version >> $GITHUB_OUTPUT
        name: Push Tag
        shell: bash
